# Generated by Django 3.0.5 on 2020-04-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('datos_adicionales', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('estado', models.BooleanField(choices=[(1, 'Fijo'), (2, 'Eventual')])),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prioridad', models.CharField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], max_length=100)),
                ('estado', models.CharField(choices=[(1, 'Sin empezar'), (2, 'En marcha'), (3, 'Acabada')], max_length=100)),
                ('notas', models.CharField(max_length=10000)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Cliente')),
                ('empleados', models.ManyToManyField(to='myApp.Empleado')),
                ('tareas', models.ManyToManyField(to='myApp.Tarea')),
            ],
        ),
    ]
