# Generated by Django 3.0.5 on 2020-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
