# Generated by Django 3.0.5 on 2020-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200415_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[(0, 'Sin empezar'), (1, 'En marcha'), (2, 'Acabada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[(0, 'Alta'), (1, 'Media'), (2, 'Baja')], max_length=100),
        ),
    ]
