# Generated by Django 3.0.5 on 2020-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20200416_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Sin empezar'), (1, 'En marcha'), (2, 'Acabada')]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Alta'), (1, 'Media'), (2, 'Baja')]),
        ),
    ]
