# Generated by Django 3.0.5 on 2020-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20200416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='datos_adicionales',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='notas',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
